version: '3.5'

services:
  sqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: St0Ck4Ss!sT
      MYSQL_DATABASE: StockAssistantDB

  adminer:
    image: adminer
    restart: always
    ports:
    - 8083:8080

  mongo:
    build: ./MongoDBDockerFile
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: stockassist

  wait-for-it:
    image: willwill/wait-for-it
    entrypoint: "./wait-for-it.sh -t 300 sqldb:3306 --strict"

  stock_assistant_api:
    build: .
    ports:
    - 443:443
    depends_on:
      - sqldb
    restart: on-failure